using System.Numerics;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampWidget : PanelContainer
{
    private static readonly ProtoId<ShaderPrototype> PaperStamp = "PaperStamp";

    private readonly StyleBoxTexture _borderTexture;
    private readonly ShaderInstance? _stampShader;

    // WL-Changes-start
    private readonly SpriteSystem _sprite;
    // WL-Changes-end

    public float Orientation
    {
        get => StampedByLabel.Orientation;
        set => StampedByLabel.Orientation = value;
    }

    // WL-Changes-start
    //public StampDisplayInfo StampInfo
    //{
    //    set
    //    {

    //        StampedByLabel.Text = Loc.GetString(value.StampedName);
    //        StampedByLabel.FontColorOverride = value.StampedColor;
    //        ModulateSelfOverride = value.StampedColor;
    //    }
    //}
    // WL-Changes-end

    public StampWidget()
    {
        RobustXamlLoader.Load(this);

        // WL-Changes-start
        _sprite = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();

        _borderTexture = new StyleBoxTexture();
        // WL-Changes-end

        _borderTexture.SetPatchMargin(StyleBoxTexture.Margin.All, 7.0f);
        PanelOverride = _borderTexture;

        var prototypes = IoCManager.Resolve<IPrototypeManager>();
        _stampShader = prototypes.Index(PaperStamp).InstanceUnique();
    }

    // WL-Changes-start
    public void UpdateVisuals(StampDisplayInfo stampInfo)
    {
        var texture = _sprite.Frame0(stampInfo.StampedTexture);

        _borderTexture.Texture = texture;

        ModulateSelfOverride = stampInfo.StampedColor;

        StampedByLabel.Visible = stampInfo.StampedTextureIsBorder;
        StampedByLabel.Text = Loc.GetString(stampInfo.StampedName);
        StampedByLabel.FontColorOverride = stampInfo.StampedColor;
    }
    // WL-Changes-end

    protected override void Draw(DrawingHandleScreen handle)
    {
        _stampShader?.SetParameter("objCoord", GlobalPosition * UIScale * new Vector2(1, -1));
        handle.UseShader(_stampShader);
        handle.SetTransform(GlobalPosition * UIScale, Orientation, Vector2.One);
        base.Draw(handle);

        // Restore a sane transform+shader
        handle.SetTransform(Matrix3x2.Identity);
        handle.UseShader(null);
    }
}
